name: Get K8s-cluster-namespace-check

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  login:
    uses: ./.github/workflows/K8S-cluster-namespace-check-V1.yml
    with:
      azureResourceGroup: "petclinic-rg"
      kubernetesCluster: "petclinic-aks"
      kubernetesNamespace: "kube-system"
      azureSubscription: "208b0fcb-4e22-483d-a26c-81f93469a453"
