name: Azure Login

on:
  push:
    branches:
      - NA

jobs:
  login-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Add additional steps here that require Azure login
    - name: Azure CLI example
      run: |
        az account show
