
name: AzureLoginSample

on:
  push:
    branches:
      - stage
  workflow_dispatch:


jobs:

  build-and-deploy-latest:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
