name: login acr

on:
  push:
    branches:
      - stage

jobs:
  login-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to ACR
      uses: ./.github/workflows/Login-Azure-Container-Registry-v2.yml
      with:
        login_server: manishkr.azurecr.io
