name: Build and Push Docker Image

on:
  push:
    branches:
      - stage

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: <your-acr-login-server>
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
