name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - stage

jobs:
  clone-repo:
    uses: ./.centralworkflow/.github/workflows/clone-repo.yml
    with:
      repo_url: "https://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@github.com/manishkr5470/spring-petclinic.git"  # Replace with actual repo URL
      branch: "stage"  # Adjust branch as needed
      
  login-acr:
    needs: clone-repo
    uses: ./.github/workflows/Login-Azure-Container-Registry-v2.yml
    with:
      dockerRegistryServiceConnection: "manishkr.azurecr.io"  # Replace with actual ACR login server
    secrets:
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}

  build-and-push:
    needs: login-acr
    uses: ./.github/workflows/docker_build.yml
    with:
      image_name: "spring"  # Replace with your image name
      image_tag: "latest"
      docker_registry: "manishkr.azurecr.io"  # Replace with actual ACR login server


