name: Reusable Docker Build and Push

on:
  workflow_call:  # Allows this workflow to be reused
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: false
        default: "latest"
        type: string
      docker_registry:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ inputs.image_name }}
      IMAGE_TAG: ${{ inputs.image_tag }}
      DOCKER_REGISTRY: ${{ inputs.docker_registry }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: |
          echo "InPuepYJgi0dOVWU656fdedt8sirs+Y1NPwb3aw/qw+ACRDgLO5c" | docker login $DOCKER_REGISTRY -u "manishkr" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Log out from Docker Registry
        run: docker logout $DOCKER_REGISTRY
