name: Reusable Login to Container Registry

on:
  workflow_call:
    inputs:
      dockerRegistryServiceConnection:
        required: true
        type: string

jobs:
  login-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Check if ACR_USERNAME secret is available
        run: |
         echo "My secret is: ${{ secrets.ACR_USERNAME }}"

        
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.dockerRegistryServiceConnection }}
          username: manishkr
          password: InPuepYJgi0dOVWU656fdedt8sirs+Y1NPwb3aw/qw+ACRDgLO5c
