name: Login to Azure Container Registry

on:
  workflow_call:
    inputs:
      login_server:
        description: 'Azure Container Registry Login Server'
        required: true
        type: string
      username:
        description: 'Azure Container Registry Username'
        required: true
        type: string
    secrets:
      password:
        description: 'Azure Container Registry Password'
        required: true

jobs:
  login-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.password }}" | docker login ${{ inputs.login_server }} -u ${{ inputs.username }} --password-stdin

      - name: Verify Login
        run: |
          docker info
