name: Login to Azure Container Registry

on:
  workflow_call:
    inputs:
      dockerRegistryServiceConnection:
        description: 'Azure Container Registry Login Server'
        required: true
        type: string
      acr_password:
        description: 'Azure Container Registry Password'
        required: true
        type: string  
      acr_username:
        description: 'Azure Container Registry Username'
        required: true
        type: string
  
      
        


jobs:
  login-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        run: |
          echo "${{  inputs.acr_password }}" | docker login ${{ inputs.dockerRegistryServiceConnection }} -u ${{  inputs.acr_username }} --password-stdin

      - name: Verify Login
        run: |
          docker info
