name: Login to Azure Container Registry

on:
  workflow_call:
    inputs:
      login_server:
        description: 'Azure Container Registry Login Server'
        required: true
        type: string


jobs:
  login-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        run: |
          echo "${{  secrets.ACR_PASSWORD }}" | docker login ${{ inputs.login_server }} -u ${{  secrets.ACR_USERNAME }} --password-stdin

      - name: Verify Login
        run: |
          docker info
